In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rakibulhasanshaon69/the-verdict-txt")

print("Path to dataset files:", path)

100%|██████████| 8.86k/8.86k [00:00<00:00, 11.9MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/rakibulhasanshaon69/the-verdict-txt/versions/1


In [2]:
import os
import shutil

In [3]:
os.listdir(path)

['the-verdict.txt']

In [4]:
shutil.copy(os.path.join(path,"the-verdict.txt"),"/content")

'/content/the-verdict.txt'

In [5]:
with open("the-verdict.txt","r",encoding="utf-8") as f:
  raw_text=f.read()

In [6]:
raw_text

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [7]:

import re # for spliting text

text="Hello,World, This, is a test."
result=re.split(r'(\s)',text)
print(result)



['Hello,World,', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']


In [8]:

import re # for spliting text

text="Hello,World, This, is a test."
result=re.split(r'([,.]\s)',text)
print(result)



['Hello,World', ', ', 'This', ', ', 'is a test.']


In [9]:
result=[r for r in result if r.strip()]

In [10]:
result

['Hello,World', ', ', 'This', ', ', 'is a test.']

In [11]:

import re # for spliting text

text="Hello,World, This, is a test."
result=re.split(r'([,.:;?_!"()\']\s)',text)
result=[r for r in result if r.strip()]
print(result)



['Hello,World', ', ', 'This', ', ', 'is a test.']


In [12]:

import re # for spliting text

result=re.split(r'([,.:;?_!"()\' ]|--|\s)',raw_text)
result=[r for r in result if r.strip()]
print(result)



['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--', 'deploring', 'his', 'unaccountable', 'abdication', '.', '"', 'Of', 'course', 'it', "'", 's', 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'", 'way', 'up', ';', 'but', 'I', 'don', "'", 't', 'think', 'of', 'that', ',

In [13]:
len(result)

4690

In [14]:
result=sorted(set(result))
result.extend(['<|endoftoken|>','<|unk|>']) # the end two extra tokens

all_words=list(enumerate(result))

print("len of vocab",len(all_words))

all_words=dict(all_words)

len of vocab 1132


In [15]:
all_words

{0: '!',
 1: '"',
 2: "'",
 3: '(',
 4: ')',
 5: ',',
 6: '--',
 7: '.',
 8: ':',
 9: ';',
 10: '?',
 11: 'A',
 12: 'Ah',
 13: 'Among',
 14: 'And',
 15: 'Are',
 16: 'Arrt',
 17: 'As',
 18: 'At',
 19: 'Be',
 20: 'Begin',
 21: 'Burlington',
 22: 'But',
 23: 'By',
 24: 'Carlo',
 25: 'Chicago',
 26: 'Claude',
 27: 'Come',
 28: 'Croft',
 29: 'Destroyed',
 30: 'Devonshire',
 31: 'Don',
 32: 'Dubarry',
 33: 'Emperors',
 34: 'Florence',
 35: 'For',
 36: 'Gallery',
 37: 'Gideon',
 38: 'Gisburn',
 39: 'Gisburns',
 40: 'Grafton',
 41: 'Greek',
 42: 'Grindle',
 43: 'Grindles',
 44: 'HAD',
 45: 'Had',
 46: 'Hang',
 47: 'Has',
 48: 'He',
 49: 'Her',
 50: 'Hermia',
 51: 'His',
 52: 'How',
 53: 'I',
 54: 'If',
 55: 'In',
 56: 'It',
 57: 'Jack',
 58: 'Jove',
 59: 'Just',
 60: 'Lord',
 61: 'Made',
 62: 'Miss',
 63: 'Money',
 64: 'Monte',
 65: 'Moon-dancers',
 66: 'Mr',
 67: 'Mrs',
 68: 'My',
 69: 'Never',
 70: 'No',
 71: 'Now',
 72: 'Nutley',
 73: 'Of',
 74: 'Oh',
 75: 'On',
 76: 'Once',
 77: 'Only',
 7

In [16]:
from typing import List
import re

class SentenceTokenizerV1:
  def __init__(self,vocab:dict):
    self.int_to_str=vocab
    self.str_to_int={v:k for k,v in vocab.items()}


  def encode(self,text:str):
    text=re.split(r'([,.:;?_!"()\']|--|\s)',text)
    text=[r for r in text if r.strip()]
    # Correcting the syntax for handling unknown tokens
    text=[t if t in self.str_to_int else '<|unk|>' for t in text]

    tokens=[self.str_to_int[t] for t in text]

    return tokens

  def decode(self,tokens:List[int]):

    text=" ".join([self.int_to_str[t] for t in tokens])

    text = re.sub(r'\s+([,.?!"()\[\]{}])', r'\1', text)
    text = re.sub(r'\s+(--)\s*', r'\1', text)
    text = re.sub(r'\s+(\'s|\'t|\'re|\'ve|\'ll|\'d)', r'\1', text)

    return text

In [17]:
tokenizer=SentenceTokenizerV1(all_words)


In [18]:
text="I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped h"
text

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped h'

In [19]:
tokens=tokenizer.encode(text)
tokens

[53,
 44,
 149,
 1003,
 57,
 38,
 818,
 115,
 256,
 486,
 6,
 1002,
 115,
 500,
 435,
 392,
 6,
 908,
 585,
 1077,
 709,
 508,
 961,
 1016,
 663,
 1016,
 535,
 987,
 5,
 568,
 988,
 538,
 722,
 549,
 496,
 5,
 533,
 514,
 370,
 1131]

In [20]:
tokenizer.decode(tokens)

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped <|unk|>'

In [21]:
tokenizer.encode("<|endoftoken|>".join([text,text]))

[53,
 44,
 149,
 1003,
 57,
 38,
 818,
 115,
 256,
 486,
 6,
 1002,
 115,
 500,
 435,
 392,
 6,
 908,
 585,
 1077,
 709,
 508,
 961,
 1016,
 663,
 1016,
 535,
 987,
 5,
 568,
 988,
 538,
 722,
 549,
 496,
 5,
 533,
 514,
 370,
 1131,
 44,
 149,
 1003,
 57,
 38,
 818,
 115,
 256,
 486,
 6,
 1002,
 115,
 500,
 435,
 392,
 6,
 908,
 585,
 1077,
 709,
 508,
 961,
 1016,
 663,
 1016,
 535,
 987,
 5,
 568,
 988,
 538,
 722,
 549,
 496,
 5,
 533,
 514,
 370,
 1131]

In [22]:
import tiktoken
import importlib

In [23]:
print("tiktoken version:",importlib.metadata.version("tiktoken"))

tiktoken version: 0.12.0


In [24]:
tokenizer=tiktoken.get_encoding("gpt2")

In [25]:
text=(
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
    "of someunknownPlace."

)

integers=tokenizer.encode(text=text,allowed_special={"<|endoftext|>"})
integers

[15496,
 11,
 466,
 345,
 588,
 8887,
 30,
 220,
 50256,
 554,
 262,
 4252,
 18250,
 8812,
 2114,
 1659,
 617,
 34680,
 27271,
 13]

In [26]:
tokenizer.decode(integers)

'Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.'

# Coding Input_Output Pairs

In [27]:
from torch.utils.data import Dataset,DataLoader

In [28]:
class GPTDatasetV1(Dataset):
  def __init__(self,txt,tokenizer,max_len,stride):

    self.input_ids=[]
    self.output_ids=[]


    token_ids=tokenizer.encode(txt,allowed_special={"<|endoftext|>"})
    for i in range(0,len(token_ids)-max_len,stride):
      self.input_ids.append(token_ids[i:i+max_len])
      self.output_ids.append(token_ids[i+1:i+max_len+1])


  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self,idx):
    return {"input_ids":self.input_ids[idx],"output_ids":self.output_ids[idx]}

In [30]:
GPTDatasetV1(txt=text,tokenizer=tokenizer,max_len=4,stride=1)[0]

{'input_ids': [15496, 11, 466, 345], 'output_ids': [11, 466, 345, 588]}

In [38]:
def create_GPTDatasetV1_loader(txt,max_len,stride,batch_size,shuffle=True,drop_last=True,num_workers=0):
  tokenizer=tiktoken.get_encoding("gpt2")
  data_loader=DataLoader(GPTDatasetV1(txt=txt,tokenizer=tokenizer,max_len=max_len,stride=stride),batch_size=batch_size,shuffle=shuffle,drop_last=drop_last,num_workers=num_workers)
  return data_loader

In [39]:
dataset_loader=create_GPTDatasetV1_loader(txt=text,max_len=4,stride=1,batch_size=2)

In [40]:
for _ in dataset_loader:
  print(_)

{'input_ids': [tensor([466, 262]), tensor([ 345, 4252]), tensor([  588, 18250]), tensor([8887, 8812])], 'output_ids': [tensor([ 345, 4252]), tensor([  588, 18250]), tensor([8887, 8812]), tensor([  30, 2114])]}
{'input_ids': [tensor([ 1659, 18250]), tensor([ 617, 8812]), tensor([34680,  2114]), tensor([27271,  1659])], 'output_ids': [tensor([ 617, 8812]), tensor([34680,  2114]), tensor([27271,  1659]), tensor([ 13, 617])]}
{'input_ids': [tensor([15496,  4252]), tensor([   11, 18250]), tensor([ 466, 8812]), tensor([ 345, 2114])], 'output_ids': [tensor([   11, 18250]), tensor([ 466, 8812]), tensor([ 345, 2114]), tensor([ 588, 1659])]}
{'input_ids': [tensor([345, 554]), tensor([588, 262]), tensor([8887, 4252]), tensor([   30, 18250])], 'output_ids': [tensor([588, 262]), tensor([8887, 4252]), tensor([   30, 18250]), tensor([ 220, 8812])]}
{'input_ids': [tensor([50256,   220]), tensor([  554, 50256]), tensor([262, 554]), tensor([4252,  262])], 'output_ids': [tensor([  554, 50256]), tensor([2

In [41]:
data_itr=iter(dataset_loader)

In [43]:
next(data_itr)

{'input_ids': [tensor([15496,  8887]),
  tensor([11, 30]),
  tensor([466, 220]),
  tensor([  345, 50256])],
 'output_ids': [tensor([11, 30]),
  tensor([466, 220]),
  tensor([  345, 50256]),
  tensor([588, 554])]}

In [46]:
next(data_itr)

{'input_ids': [tensor([588, 554]),
  tensor([8887,  262]),
  tensor([  30, 4252]),
  tensor([  220, 18250])],
 'output_ids': [tensor([8887,  262]),
  tensor([  30, 4252]),
  tensor([  220, 18250]),
  tensor([50256,  8812])]}